name: Deploy to GitHub Pages (Auto)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Switch to local mode
        run: |
          echo "🔍 Before switch - .npmrc content:"
          cat .npmrc || echo "No .npmrc file found"
          node scripts/switch-mode.js local
          echo "🔍 After switch - .npmrc content:"
          cat .npmrc || echo "No .npmrc file found"

      - name: Configure NPM registry
        run: |
          echo "🔍 Current .npmrc content:"
          cat .npmrc || echo "No .npmrc file found"
          npm config delete registry || true
          npm config set registry https://registry.npmjs.org/
          npm config list
          echo "Registry: $(npm config get registry)"
          
      - name: Install shared dependencies
        run: |
          cd shared
          rm -f package-lock.json
          npm config delete registry || true
          npm config set registry https://registry.npmjs.org/
          npm install --legacy-peer-deps
          
      - name: Install root dependencies
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Install all app dependencies manually
        run: |
          # Install each app individually to avoid npm ci with cached Nexus URLs
          for app in single-spa-auth-app single-spa-layout-app single-spa-home-app single-spa-angular-app single-spa-vue-app single-spa-react-app single-spa-vanilla-app single-spa-webcomponents-app single-spa-typescript-app single-spa-jquery-app single-spa-svelte-app; do
            echo "📦 Installing dependencies for $app"
            cd $app
            rm -f package-lock.json
            npm config delete registry || true
            npm config set registry https://registry.npmjs.org/
            npm install --legacy-peer-deps
            cd ..
          done

      - name: Build all applications
        run: |
          # Build each app individually
          for app in single-spa-auth-app single-spa-layout-app single-spa-home-app single-spa-angular-app single-spa-vue-app single-spa-react-app single-spa-vanilla-app single-spa-webcomponents-app single-spa-typescript-app single-spa-jquery-app single-spa-svelte-app; do
            echo "🔨 Building $app"
            cd $app
            npm run build:prod
            cd ..
          done

      - name: Deploy all to GitHub Pages
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          ORG_NAME: ${{ secrets.ORG_NAME || github.repository_owner }}
        run: |
          # Debug: Check if token is available
          echo "🔍 Debug: GITHUB_API_TOKEN length: ${#GITHUB_API_TOKEN}"
          if [ -z "$GITHUB_API_TOKEN" ]; then
            echo "❌ GH_API_TOKEN secret is empty or not set"
            echo "📝 Please check: https://github.com/${{ github.repository_owner }}/demo-microfrontends/settings/secrets/actions"
            exit 1
          fi
          
          # Make scripts executable
          chmod +x ./scripts/deploy-github.sh
          chmod +x ./scripts/create-github-repo.sh
          
          # Deploy each microfrontend
          ./scripts/deploy-github.sh single-spa-auth-app
          ./scripts/deploy-github.sh single-spa-layout-app
          ./scripts/deploy-github.sh single-spa-home-app
          ./scripts/deploy-github.sh single-spa-angular-app
          ./scripts/deploy-github.sh single-spa-vue-app
          ./scripts/deploy-github.sh single-spa-react-app
          ./scripts/deploy-github.sh single-spa-vanilla-app
          ./scripts/deploy-github.sh single-spa-webcomponents-app
          ./scripts/deploy-github.sh single-spa-typescript-app
          ./scripts/deploy-github.sh single-spa-jquery-app
          ./scripts/deploy-github.sh single-spa-svelte-app
          
          # Deploy root application
          ./scripts/deploy-github.sh root