name: Deploy Svelte App

on:
  push:
    branches: [main, master]
    paths: ['single-spa-svelte-app/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    defaults:
      run:
        working-directory: single-spa-svelte-app
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.8'
        cache: 'npm'
        cache-dependency-path: single-spa-svelte-app/package-lock.json

    - name: Configure NPM registry
      run: |
        npm config delete registry || true
        npm config set registry https://registry.npmjs.org/
        npm config list
        echo "Registry: $(npm config get registry)"

    - name: Clear npm cache and lock file
      run: |
        npm cache clean --force
        rm -f package-lock.json

    - name: Switch to local mode
      run: |
        cd ..
        node scripts/switch-mode.js local
        
    - name: Install shared dependencies
      run: |
        cd ../shared
        npm install --legacy-peer-deps
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: |
        export NODE_OPTIONS="--openssl-legacy-provider"
        npm run build:prod
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'eu-central-1' }}
        
    - name: Deploy to S3 and update import map
      run: |
        export GITHUB_SHA=${{ github.sha }}
        chmod +x ../scripts/deploy.sh
        ../scripts/deploy.sh svelte-app single-spa-svelte-app.js '{}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION || 'eu-central-1' }}
        ORG_NAME: ${{ secrets.ORG_NAME }}